---
title: "JPMC DataHack"
author: "Neel Mirani"
date: "9/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(plotly)
```

```{r}
NYCSchools <- read_excel("NYC Schools -2021 Hackathon.xlsx")
studentRating <- read_excel("NYC Schools -2021 Hackathon.xlsx", sheet = 4)
TotalGenEd <- read_excel("NYC Schools -2021 Hackathon.xlsx", sheet = 2)
```


```{r}
NYCSchools$`Averaged Test Scores(ELA and Math)` = (as.numeric(NYCSchools$`Average ELA Proficiency`) + as.numeric(NYCSchools$`Average Math Proficiency`))/2
head(NYCSchools)
head(studentRating)

NYCSchools1 <- NYCSchools %>%
  mutate(`Percent of Students Chronically Absent` = round(100 * as.numeric(`Percent of Students Chronically Absent`),2))%>%
  filter(!is.na(`Percent of Students Chronically Absent`))

simplePlot <- ggplot(NYCSchools1, aes(x = `Percent of Students Chronically Absent`, y = `Averaged Test Scores(ELA and Math)`)) + geom_point() + ggtitle("Relationship betwen Absenteeism and Test Scores");
simplePlot <- ggplotly(simplePlot)
simplePlot

```

```{r}
TotalGenEd <- TotalGenEd %>%
  mutate(`School Name` = toupper(`School Name`))
studentRating <- studentRating %>%
  mutate(`School Name` = toupper(`School Name`))

dataMerge2 <- inner_join(TotalGenEd, studentRating, by = "School Name")

dataMerge2 <- dataMerge2 %>%
select(`School Name`, `1a. This school offers a wide enough variety of programs, classes and activities to keep me interested in school.`, `Percent Satisfaction: Student`)%>%
  rename(`Strongly Disagree Variety of Programs/Classes/Activities` = `1a. This school offers a wide enough variety of programs, classes and activities to keep me interested in school.`) %>%
  mutate(`Percent Satisfaction: Student` = round(as.numeric(`Percent Satisfaction: Student`), 2))%>%
  mutate(`Percent who Strongly Disagree with the presence of a Variety of Programs/Classes/Activities: Student` = round(as.numeric(`Strongly Disagree Variety of Programs/Classes/Activities`), 2))

dataMerge2

plot2 <- ggplot(dataMerge2, aes(y = `Percent Satisfaction: Student`, x = `Percent who Strongly Disagree with the presence of a Variety of Programs/Classes/Activities: Student`)) + geom_point() + ggtitle("Variety of Offerings on Student Satisfaction")
ggplotly(plot2)
```


```


